### ISSUE TITLE
feature request: In hand pose add ability to detect space between fingers.

### ISSUE THREAD

**Issue by delebash** [vladmandic/precision-human#4]
When producing the 3D data add ability to produce data as what you see demo view.  Example would be the spreading of my fingers I would need that information to animate the hand correctly for the 3D character.

**Comment by vladmandic** [comment]
coordinates are already there, that is a simple math and typical method is to calculate euclidean distance.
e.g., if a and b are points and each have x,y,z coordinates, then

distance = sqrt( (ax - bx)^2 + (ay - by)^2 + (ay - zy)^2 )

**Comment by delebash** [comment]
ok!

**Comment by vladmandic** [comment]
take a look at `embedding.js:simmilarity()`, i use it for a different purpose, but that is optimized way to calculate euclidean distance.

**Comment by delebash** [comment]
ok thanks
